version: '3'
services:
  covid-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: covid-dashboard
    container_name: covid-dashboard
    ports:
      - 3007:3000
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: covid-dash.myms.smartyotta.com
      VIRTUAL_PORT: 3007
      LETSENCRYPT_HOST: covid-dash.myms.smartyotta.com
      LETSENCRYPT_EMAIL: mohammedsalaah96@gmail.com
networks:
  default:
    external:
      name: nginx-proxy


